baseURL = 'https://danielchg.github.io/'
languageCode = 'en-us'
title = 'Daniel Ops'
theme = "m10c"

[params]
  author = 'Daniel Chavero Gaspar'
  description = 'A blog about whatever OPS!!'
  avatar = 'login-pic.jpg'
  menu_item_separator = '|'

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 100

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[[menu.main]]
  identifier = "about me"
  name = "About Me"
  url = "/about/"
  weight = 200

[[params.social]]
  icon = 'twitter'
  name = 'twitter'
  url = 'https://twitter.com/dani_chg'

[[params.social]]
  icon = 'github'
  name = 'github'
  url = 'https://github.com/danielchg'

[[params.social]]
  icon = 'linkedin'
  name = 'linkedin'
  url = 'https://www.linkedin.com/in/daniel-chavero-gaspar-19107613/'
